htm_user:
    resource: "@HTMUserBundle/Resources/config/routing.yml"

htm_cinema:
    resource: "@HTMCinemaBundle/Resources/config/routing.yml"

htm_core:
    resource: "@HTMCoreBundle/Resources/config/routing.yml"
