# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        HTM\UserBundle\Entity\User: sha512

    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                # Cela permet de valider les informations saisies par les utilisateurs (Par Symfony)
                check_path: fos_user_security_check
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
                use_referer: false
            logout:
                path:   fos_user_security_logout
                target: /login
            remember_me:
                secret:   '%kernel.secret%' # %secret% est un paramètre de parameters.yml
            
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
