<?php

namespace HTM\CinemaBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFilm($film)
    {
        return $this->createQueryBuilder('c')
                    ->select("c.comment")
                    ->where('c.film = :film')
                    ->setParameters(array('film'=>$film))
                    ->getQuery()
                    ->getResult();
    }
}
