<?php

namespace HTM\CoreBundle\Repository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSlide()
	{
		return $this->createQueryBuilder('s')
					->getQuery()
					->getResult();
	}
}
